version: "3.3"

services:
  db:
    container_name: postgres
    restart: always
    image: postgres:latest
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: root
    volumes:
       # To persist your data
      - /postgres_data:/var/lib/postgresql
    ports:
      # <Port exposed> : < POSTGRESQL Port running inside container>
      - "3100:5432"
    expose:
      # Opens port 5432 on the container
      - "5432"
#to run stack.yml : docker-compose -f stack.yml up
#to enter to the console of the container : docker exec -it <mycontainer> bash
#to see volumenes : dcoker volume ls
