version: '3.3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3100:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'


#to run stack.yml : docker-compose -f stack.yml up