version: "3.3"

services:
  db:
    container_name: database_mysql
    restart: always
    image: mysql:latest
    environment:
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
       # To persist your data
      - /mysql_data:/var/lib/mysql
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3100:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
#to run stack.yml : docker-compose -f stack.yml up
#to enter to the console of the container : docker exec -it <mycontainer> bash
#to see volumenes : dcoker volume ls
